<?php

namespace Modules\Saas\Http\Controllers\Tenant;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Saas\Contracts\CurrentTenant;
use Modules\Saas\Contracts\TenantStorage;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Serves tenant-scoped file downloads via signed URLs.
 *
 * The URL signature includes the tenant UUID, so a URL generated for
 * Tenant A cannot be replayed on Tenant B's host. The path is encrypted
 * in the URL to prevent enumeration.
 *
 * Flow:
 *  1. TenantUrlGenerator generates a signed URL with encrypted path.
 *  2. Client requests the URL.
 *  3. This controller verifies the signature (Laravel does this via
 *     the 'signed' middleware or manual check).
 *  4. Decrypts the path and validates it belongs to the active tenant.
 *  5. Streams the file.
 */
class AssetController extends Controller
{
    public function __construct(
        private readonly CurrentTenant $currentTenant,
        private readonly TenantStorage $storage,
    ) {
    }

    /**
     * GET /saas/asset or /saas/download with an encrypted path query.
     *
     * Serves a file from the tenant's storage prefix.
     */
    public function download(Request $request): StreamedResponse
    {
        // Verify the URL signature.
        if (! $request->hasValidSignature()) {
            abort(403, 'Invalid or expired download link.');
        }

        $context = $this->currentTenant->getOrFail();
        $signedTenant = (string) $request->query('tenant', '');
        if ($signedTenant === '' || ! hash_equals($context->uuid, $signedTenant)) {
            abort(403, 'This download link belongs to a different school.');
        }
        $decryptedPath = $this->resolvePath($request);

        try {
            $relativePath = $this->storage->path($decryptedPath);
            $this->storage->assertPathBelongsToTenant($relativePath);
        } catch (\InvalidArgumentException) {
            abort(400, 'Invalid storage path.');
        }

        $disk = $this->storage->disk();

        if (! $disk->exists($relativePath)) {
            abort(404, 'File not found.');
        }

        // Determine the download filename.
        $filename = basename($decryptedPath);

        return $disk->download($relativePath, $filename);
    }

    /**
     * Resolve the actual file path from the request.
     *
     * Only encrypted paths generated by TenantUrlGenerator are accepted.
     */
    private function resolvePath(Request $request): string
    {
        $encryptedPath = $request->query('path');

        if (! is_string($encryptedPath) || $encryptedPath === '') {
            abort(400, 'Missing path parameter.');
        }

        try {
            $path = decrypt($encryptedPath);
        } catch (\Throwable) {
            abort(400, 'Invalid path parameter.');
        }

        if (! is_string($path) || $path === '') {
            abort(400, 'Invalid path parameter.');
        }

        return $path;
    }
}
