<?php

use Illuminate\Support\Facades\Route;
use Modules\Saas\Http\Controllers\Tenant\AssetController;
use Modules\Saas\Http\Controllers\Tenant\TenantInfoController;

/*
|--------------------------------------------------------------------------
| Tenant Routes
|--------------------------------------------------------------------------
| These routes run on TENANT hosts only ({tenant}.product.example or a
| verified custom domain). They are registered AFTER the ResolveTenant
| middleware has identified and initialized the tenant context.
|
| The existing ERP routes (web.php, api.php, site.php, etc.) continue to
| serve the school management application. These routes add SaaS-specific
| tenant endpoints that the core ERP does not own.
|
| IMPORTANT: These routes must NEVER query the landlord database directly
| from a controller. Use the injected contracts (CurrentTenant,
| EntitlementChecker, TenantStorage, TenantUrlGenerator) which handle
| landlord lookups safely.
*/

Route::prefix('saas')
    ->middleware(['saas.tenant-host', 'saas.tenant-active'])
    ->name('saas.tenant.')
    ->group(function () {

        // Tenant identity and entitlement info for the Flutter/mobile client.
        // The client uses this to validate its stored tenant context matches
        // the server and to discover available features.
        Route::get('/info', [TenantInfoController::class, 'show'])
            ->name('info');

        // Current entitlement snapshot (cached, plan-aware).
        Route::get('/entitlements', [TenantInfoController::class, 'entitlements'])
            ->name('entitlements');

        // Signed asset download. The URL is generated by TenantUrlGenerator
        // and includes the tenant UUID in the signature.
        Route::get('/asset/{path}', [AssetController::class, 'download'])
            ->where('path', '.*')
            ->name('asset');

        // Signed file download (exports, reports, documents).
        Route::get('/download/{path}', [AssetController::class, 'download'])
            ->where('path', '.*')
            ->name('download');
    });
