<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Where a tenant's data physically lives.
 *
 * CREDENTIALS ARE NEVER STORED HERE (plan §5.1). `secret_ref` is a pointer
 * into a secret manager — an ARN, a Vault path, or in local development an env
 * var name. Anyone who dumps this table gets no way into a tenant database.
 *
 * `database_name` is generated by the provisioner from the tenant UUID. It is
 * never accepted from request input, because a request-controlled database
 * name is a direct path to reading another tenant.
 */
return new class extends Migration
{
    public function getConnection(): string
    {
        return config('saas.database.landlord_connection', 'landlord');
    }

    public function up(): void
    {
        Schema::connection($this->getConnection())->create('saas_tenant_databases', function (Blueprint $table) {
            $table->id();
            $table->uuid('tenant_uuid')->unique();

            // Logical cluster/host identifier, resolved to a real endpoint
            // through config rather than stored as a raw address.
            $table->string('cluster', 64)->default('default')->index();

            $table->string('database_name', 64)->unique();

            // Pointer to the secret, not the secret.
            $table->string('secret_ref', 255);

            // Schema version applied to THIS database. Drives batched
            // migration rollout and tells you which tenants are behind.
            $table->string('schema_version', 40)->nullable()->index();
            $table->string('app_version', 40)->nullable();

            $table->string('health_status', 20)->default('unknown');
            $table->timestamp('last_checked_at')->nullable();
            $table->timestamp('last_migrated_at')->nullable();

            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::connection($this->getConnection())->dropIfExists('saas_tenant_databases');
    }
};
